name: Check processor on PR
on:
  pull_request:
    branches:
      - "**"
    paths:
      - "processor/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: processor

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Load env
        run: cp .env.example .env

      - name: Install dependencies
        run: bun install

      - name: Type check
        run: bun run --check
